#pragma once

typedef enum
{
	TIFF_STATUS_OK = 0,

	TIFF_ERR_USELESS_HDL = -1,
	TIFF_ERR_READ_DATA_FROM_FILE_FAILED = -2,
	TIFF_ERR_OPEN_FILE_PARAMETER_ERROR = -3,
	TIFF_ERR_OPEN_FILE_FAILED = -4,
	TIFF_ERR_CLOSE_FILE_FAILED = -5,
	TIFF_ERR_NO_TIFF_FORMAT = -6,
	TIFF_ERR_BLOCK_SIZE_IN_IFD_IS_EMPTY = -7,
	TIFF_ERR_NEED_IFD_NOT_FOUND = -8,
	TIFF_ERR_BLOCK_OUT_OF_RANGE = -9,
	TIFF_ERR_NO_IFD_FOUND = -10,
	TIFF_ERR_FIRST_IFD_STRUCT_NOT_COMPLETE = -11,
	TIFF_ERR_BLOCK_OFFSET_OUT_OF_RANGE = -12,
	TIFF_ERR_TAG_NOT_FOUND = -13,
	TIFF_ERR_BAD_PARAMETER_VALUE = -14,
	TIFF_ERR_IFD_ALREADY_EXIST = -15,
	TIFF_ERR_IFD_OUT_OF_DIRECTORY = -16,
	TIFF_ERR_IFD_FULL = -17,
	TIFF_ERR_UNSUPPORTED_BITS_PER_SAMPLE = -18,
	TIFF_ERR_PREVIOUS_IFD_NOT_CLOSED = -19,
	TIFF_ERR_TAG_TYPE_INCORRECT = -20,
	TIFF_ERR_TAG_SIZE_INCORRECT = -21,
	TIFF_ERR_SEEK_FILE_POINTER_FAILED = -22,
	TIFF_ERR_ALLOC_MEMORY_FAILED = -23,
	TIFF_ERR_WRONG_OPEN_MODE = -24,
	TIFF_ERR_APPEND_TAG_NOT_ALLOWED = -25,
	TIFF_ERR_DUPLICATE_WRITE_NOT_ALLOWED = -26,
	TIFF_ERR_BIGENDIAN_NOT_SUPPORT = -27,
}TiffErrorCode;
